id = "move-zed-extension"
name = "Move"
version = "0.0.1"
schema_version = 1
authors = ["Alexandros Tzimas <alex.tzimas@mystenlabs.com>"]
description = "Move language support for the zed editor."
repository = "https://github.com/mystenlabs/move-zed-extension"

[language_servers.move-analyzer]
name = "move-analyzer"
version = "1.0.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "A language server for Move"
repository = "https://github.com/MystenLabs/sui/tree/main/external-crates/move/crates/move-analyzer"
license = "Apache-2.0"
publish = false
edition = "2021"
